// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTQamGJaM0B8EpOxFeh4WCKuKj1l3mCos',
    appId: '1:86629602490:web:06c47949780cf6d1f91e83',
    messagingSenderId: '86629602490',
    projectId: 'studybuddy-350d1',
    authDomain: 'studybuddy-350d1.firebaseapp.com',
    databaseURL: 'https://studybuddy-350d1-default-rtdb.firebaseio.com',
    storageBucket: 'studybuddy-350d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPbhDc2tg7EtTTzKKyhyjj0gOlCSK5zJ8',
    appId: '1:86629602490:android:f3704ac257f6c4c6f91e83',
    messagingSenderId: '86629602490',
    projectId: 'studybuddy-350d1',
    databaseURL: 'https://studybuddy-350d1-default-rtdb.firebaseio.com',
    storageBucket: 'studybuddy-350d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE5PGHio5v9ArUFGegejbQA7Qja-Z8NFE',
    appId: '1:86629602490:ios:46b5ab5ab068cfbff91e83',
    messagingSenderId: '86629602490',
    projectId: 'studybuddy-350d1',
    databaseURL: 'https://studybuddy-350d1-default-rtdb.firebaseio.com',
    storageBucket: 'studybuddy-350d1.appspot.com',
    iosClientId: '86629602490-gbgg1vnnf1956fao8of1b41jloijpq6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.studybuddy',
  );
}
